import {BlockType, ComponentType} from './models';
import {
    Section,
    Text,
    Container,
    Header,
    HeaderBreadcrumbs,
    Button,
    Title,
    Divider,
    Features,
    Tabs,
    Share,
    Link,
    FileLink,
    Table,
    ImageBlock,
    Scrollable,
    Tiles,
    Partner,
    PriceDetailed,
    MediaCard,
    NewsCard,
    TutorialCard,
    CardWithImage,
    BackgroundCard,
    Content,
    Quote,
    Author,
} from './components';

import {
    BannerBlock,
    CompaniesBlock,
    SimpleBlock,
    MediaBlock,
    PreviewBlock,
    InfoBlock,
    SecurityBlock,
    SliderBlock,
    ExtendedFeaturesBlock,
    PromoFeaturesBlock,
    QuestionsBlock,
    TableBlock,
    TabsBlock,
    LinkTableBlock,
    HeaderBlock,
    IconsBlock,
    HeaderSliderBlock,
    CardLayoutBlock,
    ContentLayoutBlock,
} from './blocks';

const components = {
    [ComponentType.Section]: Section,
    [ComponentType.Text]: Text,
    [ComponentType.Container]: Container,
    [ComponentType.Header]: Header,
    [ComponentType.HeaderBreadcrumbs]: HeaderBreadcrumbs,
    [ComponentType.Button]: Button,
    [ComponentType.Title]: Title,
    [ComponentType.Divider]: Divider,
    [ComponentType.Features]: Features,
    [ComponentType.Tabs]: Tabs,
    [ComponentType.Share]: Share,
    [ComponentType.Link]: Link,
    [ComponentType.FileLink]: FileLink,
    [ComponentType.Table]: Table,
    [ComponentType.Image]: ImageBlock,
    [ComponentType.Scrollable]: Scrollable,
    [ComponentType.Tiles]: Tiles,
    [ComponentType.TutorialCard]: TutorialCard,
    [ComponentType.Partner]: Partner,
    [ComponentType.PriceDetailed]: PriceDetailed,
    [ComponentType.MediaCard]: MediaCard,
    [ComponentType.BannerCard]: BannerBlock,
    [ComponentType.NewsCard]: NewsCard,
    [ComponentType.CardWithImage]: CardWithImage,
    [ComponentType.BackgroundCard]: BackgroundCard,
    [ComponentType.Content]: Content,
    [ComponentType.Quote]: Quote,
    [ComponentType.Author]: Author,

    // Blocks
    [BlockType.SliderBlock]: SliderBlock,
    [BlockType.SimpleBlock]: SimpleBlock,
    [BlockType.ExtendedFeaturesBlock]: ExtendedFeaturesBlock,
    [BlockType.PromoFeaturesBlock]: PromoFeaturesBlock,
    [BlockType.QuestionsBlock]: QuestionsBlock,
    [BlockType.BannerBlock]: BannerBlock,
    [BlockType.CompaniesBlock]: CompaniesBlock,
    [BlockType.MediaBlock]: MediaBlock,
    [BlockType.PreviewBlock]: PreviewBlock,
    [BlockType.InfoBlock]: InfoBlock,
    [BlockType.SecurityBlock]: SecurityBlock,
    [BlockType.TableBlock]: TableBlock,
    [BlockType.TabsBlock]: TabsBlock,
    [BlockType.LinkTableBlock]: LinkTableBlock,
    [BlockType.HeaderBlock]: HeaderBlock,
    [BlockType.IconsBlock]: IconsBlock,
    [BlockType.HeaderSliderBlock]: HeaderSliderBlock,
    [BlockType.CardLayoutBlock]: CardLayoutBlock,
    [BlockType.ContentLayoutBlock]: ContentLayoutBlock,
};

export default components;
