name: PR Preview Build

on:
  pull_request:

env:
  PREVIEW_DEST_PATH: /page-constructor/${{ github.event.pull_request.number }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: gravity-ui/preview-build-action@v1
        with:
          node-version: 18
