name: Release version 2.x.x.

on:
  push:
    branches: [version-2.x.x]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: gravity-ui/release-action@v1
        with:
          github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          npm-token: ${{ secrets.GRAVITY_UI_BOT_NPM_TOKEN }}
          node-version: 14
          npm-dist-tag: untagged
          default-branch: version-2.x.x
