import {BlockType, SubBlockType} from '../models';

import {
    BannerBlock,
    BannerCard,
    CardLayoutBlock,
    CompaniesBlock,
    ContentLayoutBlock,
    ExtendedFeaturesBlock,
    FilterBlock,
    FoldableListBlock,
    FooterBlock,
    FormBlock,
    HeaderBlock,
    HeaderSliderBlock,
    HeroBlock,
    IconsBlock,
    InfoBlock,
    MapBlock,
    MediaBlock,
    PromoFeaturesBlock,
    QuestionsBlock,
    ShareBlock,
    SliderBlock,
    SliderOldBlock,
    TableBlock,
    TabsBlock,
} from './validators/blocks';
import {
    BackgroundCard,
    BasicCard,
    Divider,
    ImageCard,
    LayoutItemBlock,
    MediaCardBlock,
    PriceCardBlock,
    PriceDetailedBlock,
    Quote,
} from './validators/sub-blocks';

export const blockSchemas: Record<BlockType, object> = {
    ...Divider,
    ...ExtendedFeaturesBlock,
    ...PromoFeaturesBlock,
    ...SliderOldBlock,
    ...SliderBlock,
    ...QuestionsBlock,
    ...FoldableListBlock,
    ...HeaderBlock,
    ...HeroBlock,
    ...FooterBlock,
    ...BannerBlock,
    ...CompaniesBlock,
    ...MediaBlock,
    ...MapBlock,
    ...InfoBlock,
    ...TableBlock,
    ...TabsBlock,
    ...HeaderSliderBlock,
    ...IconsBlock,
    ...CardLayoutBlock,
    ...ContentLayoutBlock,
    ...ShareBlock,
    ...FilterBlock,
    ...FormBlock,
};

export const cardSchemas = {
    ...MediaCardBlock,
    ...BannerCard,
    ...PriceDetailedBlock,
    ...BackgroundCard,
    ...Quote,
    ...BasicCard,
    ...LayoutItemBlock,
    ...PriceCardBlock,
    ...ImageCard,
};

export const constructorBlockSchemaNames: string[] = [
    SubBlockType.Divider,
    BlockType.ExtendedFeaturesBlock,
    BlockType.PromoFeaturesBlock,
    BlockType.SliderOldBlock,
    BlockType.SliderBlock,
    BlockType.QuestionsBlock,
    BlockType.FoldableListBlock,
    BlockType.HeaderBlock,
    BlockType.HeroBlock,
    BlockType.FooterBlock,
    BlockType.BannerBlock,
    BlockType.CompaniesBlock,
    BlockType.MediaBlock,
    BlockType.MapBlock,
    BlockType.InfoBlock,
    BlockType.TableBlock,
    BlockType.TabsBlock,
    BlockType.HeaderSliderBlock,
    BlockType.IconsBlock,
    BlockType.CardLayoutBlock,
    BlockType.ContentLayoutBlock,
    BlockType.ShareBlock,
    BlockType.FilterBlock,
    BlockType.FormBlock,
];

export const constructorCardSchemaNames: string[] = [
    SubBlockType.MediaCard,
    SubBlockType.BannerCard,
    SubBlockType.PriceDetailed,
    SubBlockType.BackgroundCard,
    SubBlockType.Quote,
    SubBlockType.BasicCard,
    SubBlockType.LayoutItem,
    SubBlockType.PriceCard,
    SubBlockType.ImageCard,
];
